command:
  - streamlit
  - run
  - app.py
  - --server.port
  - "8501"

env:
  - name: DATABRICKS_TOKEN
    valueFrom: databricks_token_secret
  - name: DATABRICKS_HOST
    value: "https://dbc-0726d26f-3749.cloud.databricks.com"
